### ISSUE TITLE
楼主成功了吗

### ISSUE THREAD

**Issue by jdzy** [flipped-1121/UMeng#1]

**Comment by flipped-1121** [comment]
我不会 || 我懒 && 我没时间

**Comment by jdzy** [comment]
> 我不会 || 我懒 && 我没时间

原项目是Github还是CSDN,可以发下链接吗老哥

**Comment by flipped-1121** [comment]
> > 我不会 || 我懒 && 我没时间
> 
> 原项目是Github还是CSDN,可以发下链接吗老哥

原项目？？？
只写过这一个哎，也只在 [Github](https://github.com/flipped-1121/UMeng/) 平台发布过。

**Comment by jdzy** [comment]
> > > 我不会 || 我懒 && 我没时间
> > 
> > 
> > 原项目是Github还是CSDN,可以发下链接吗老哥
> 
> 原项目？？？ 只写过这一个哎，也只在 [Github](https://github.com/flipped-1121/UMeng/) 平台发布过。
不错，谢谢
